export default {
  HomeScreen: 'HomeScreen',
  PreferenceScreen: 'PreferenceScreen',
  TimelineScreen: 'TimelineScreen',
  ThreadScreen: 'ThreadScreen',
  TimelineTab: 'TimelineTab',
  CollectionScreen: 'CollectionScreen',
  CollectionTab: 'CollectionTab',
  CollectionTweetScreen: 'CollectionTweetScreen',
  SettingScreen: 'SettingScreen',
  ImageViewScreen: 'ImageViewScreen',
  DiscoverScreen: 'DiscoverScreen',
  DiscoverTab: 'DiscoverTab',
  SearchResultScreen: 'SearchResultScreen',
  ListTab: 'ListTab',
  ListScreen: 'ListScreen',
  ListTweetsScreen: 'ListTweetsScreen',
  VideoPlayerScreen: 'VideoPlayerScreen',
  LocationSelectionScreen: 'LocationSelectionScreen',
};
