export default {
  HomeScreen: 'HomeScreen',
  PreferenceScreen: 'PreferenceScreen',
  TimelineScreen: 'TimelineScreen',
  ThreadScreen: 'ThreadScreen',
  TimelineTab: 'TimelineTab',
  CollectionScreen: 'ArchiveScreen',
  CollectionTab: 'ArchiveTab',
  CollectionTweetScreen: 'ArchiveTweetScreen',
  ImageViewScreen: 'ImageViewScreen',
  DiscoverScreen: 'DiscoverScreen',
  DiscoverTab: 'DiscoverTab',
  SearchResultScreen: 'SearchResultScreen',
  ListTab: 'ListTab',
  ListScreen: 'ListScreen',
  ListTweetsScreen: 'ListTweetsScreen',
  VideoPlayerScreen: 'VideoPlayerScreen',
  LocationSelectionScreen: 'LocationSelectionScreen',
  EditListUsersScreen: 'EditListUsersScreen',
  LandingScreen: 'LandingScreen',
  ImportListScreen: 'ImportListScreen',
  ImportArchiveScreen: 'ImportArchiveScreen',
  SettingScreen: 'SettingScreen',
  BackupScreen: 'BackupScreen',
  BackupIntroductionScreen: 'BackupIntroductionScreen',
  RestoreScreen: 'RestoreScreen',
  InAppPdfViewerScreen: 'InAppPdfViewerScreen',
};
